__version__ = '0.1.0'

from .models import NCAModel, NCAModel3D, CHANNEL_N
from .training import (
    NCATrainer,
    SamplePool,
    TrainingConfig,
    load_emoji,
    load_image,
    load_image_file,
    make_seed,
    to_rgb,
    to_rgba,
    to_alpha,
    generate_video,
    generate_growth_sequence,
    tile_images,
    zoom_image,
)
from .training_3d import (
    NCATrainer3D,
    SamplePool3D,
    Training3DConfig,
    make_seed_3d,
    to_rgb_3d,
    to_rgba_3d,
    to_alpha_3d,
    make_sphere,
    make_cube,
    make_pyramid,
    make_torus,
    make_cross,
    get_target_shape,
    BUILTIN_SHAPES,
)

__all__ = [
    # Models
    "NCAModel",
    "NCAModel3D",
    "CHANNEL_N",
    # 2D Training
    "NCATrainer",
    "SamplePool",
    "TrainingConfig",
    "load_emoji",
    "load_image",
    "load_image_file",
    "make_seed",
    "to_rgb",
    "to_rgba",
    "to_alpha",
    "generate_video",
    "generate_growth_sequence",
    "tile_images",
    "zoom_image",
    # 3D Training
    "NCATrainer3D",
    "SamplePool3D",
    "Training3DConfig",
    "make_seed_3d",
    "to_rgb_3d",
    "to_rgba_3d",
    "to_alpha_3d",
    "make_sphere",
    "make_cube",
    "make_pyramid",
    "make_torus",
    "make_cross",
    "get_target_shape",
    "BUILTIN_SHAPES",
]
